### ISSUE TITLE
FATAL exception in api level 22 devices

### ISSUE THREAD

**Issue by rchamara** [amirzaidi/Shade#16]
when trying to install in Galaxy Nexus API 22 and git this error
but worked in Nexus 5X API 29 perfectly
Error:

`10/23 23:24:49: Launching Shade
No apk changes detected since last installation, skipping installation of /Users/Chamara/Documents/shade/Shade/build/outputs/apk/aosp/debug/Shade-aosp-debug.apk
$ adb shell am force-stop com.android.launcher3.debug
$ adb shell am start -n "com.android.launcher3.debug/com.android.launcher3.SettingActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Connected to process 6190 on device emulator-5556
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
E/libprocessgroup: failed to make and chown /acct/uid_10059: Read-only file system
W/Zygote: createProcessGroup failed, kernel missing CONFIG_CGROUP_CPUACCT?
I/art: Not late-enabling -Xcheck:jni (already on)
D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
D/: HostConnection::get() New Host Connection established 0xb3cf0dd0, tid 6190
D/Atlas: Validating map...
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.android.launcher3.debug, PID: 6190
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.launcher3.debug/com.android.launcher3.Launcher}: java.lang.IllegalArgumentException: No such service ComponentInfo{com.android.launcher3.debug/com.android.launcher3.uioverrides.dynamicui.WallpaperManagerCompatVL$ColorExtractionService}
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
        at android.app.ActivityThread.access$800(ActivityThread.java:151)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5254)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
     Caused by: java.lang.IllegalArgumentException: No such service ComponentInfo{com.android.launcher3.debug/com.android.launcher3.uioverrides.dynamicui.WallpaperManagerCompatVL$ColorExtractionService}
        at android.os.Parcel.readException(Parcel.java:1550)
        at android.os.Parcel.readException(Parcel.java:1499)
        at android.app.job.IJobScheduler$Stub$Proxy.schedule(IJobScheduler.java:121)
        at android.app.JobSchedulerImpl.schedule(JobSchedulerImpl.java:42)
        at com.android.launcher3.uioverrides.dynamicui.WallpaperManagerCompatVL.reloadColors(WallpaperManagerCompatVL.java:127)
        at com.android.launcher3.uioverrides.dynamicui.WallpaperManagerCompatVL.<init>(WallpaperManagerCompatVL.java:80)
        at com.android.launcher3.uioverrides.dynamicui.WallpaperManagerCompat.getInstance(WallpaperManagerCompat.java:42)
        at com.android.launcher3.uioverrides.WallpaperColorInfo.<init>(WallpaperColorInfo.java:57)
        at com.android.launcher3.uioverrides.WallpaperColorInfo.getInstance(WallpaperColorInfo.java:40)
        at com.android.launcher3.BaseDraggingActivity.onCreate(BaseDraggingActivity.java:75)
        at com.android.launcher3.Launcher.onCreate(Launcher.java:307)
        at android.app.Activity.performCreate(Activity.java:5990)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387) 
        at android.app.ActivityThread.access$800(ActivityThread.java:151) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5254) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 
Application terminated.
`

in Manifest file properties
`...
    compileSdkVersion 28
    buildToolsVersion '28.0.3'

    defaultConfig {
        minSdkVersion 21
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        vectorDrawables.useSupportLibrary = true
    }...
`

**Comment by amirzaidi** [comment]
You're trying to compile the aospDebug sourceset, set the sourceset to shadeDebug and try again. A lot of backports are done as an override from the Shade-specific sources.

**Comment by rchamara** [comment]
I move the 

<service
        android:name="com.android.launcher3.uioverrides.dynamicui.WallpaperManagerCompatVL$ColorExtractionService"
        android:exported="false"
        android:process=":wallpaper_chooser"
        android:permission="android.permission.BIND_JOB_SERVICE" />

To AndroidManifest.xml and it’s worked…
